### DISCUSSION TITLE
Pushing and pulling from within the cluster

### DISCUSSION THREAD

**Discussion by askasp** [twuni/docker-registry.helm#52] [Q&A]
Hi! I have a github action runner inside the same cluster as this docker_registry. However, i'm unable to push files to it.  As I am not leaving the cluster, I should not need an ingress.  See the path I use below. Is there anything obviously wrong here? 

    ```
    name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders
          driver-opts: network=host
          config-inline: |
              [registry."docker-registry:5000"] 
              http = true
              insecure = true

      name: Build and push to local registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker-registry:5000/app:latest 

```

This is the error I get

`Error: buildx failed with: error: failed to solve: failed to do request: Head "http://docker-registry:5000/v2/kollega/blobs/sha256:35d281021bcac4bfc59f32521d53ba1cc818f4ddacdf585fc47b5c9ffdad59f3": dial tcp: lookup docker-registry on 10.58.0.10:53: server misbehaving`
