### ISSUE TITLE
PrometheusRule cannot be created

### ISSUE THREAD

**Issue by peske** [twuni/docker-registry.helm#150]
I've tried to create a `PrometheusRule` resource by using chart, and for that reason I have the following in my values file:

```yaml
metrics:
  enabled: true
  port: 5001
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-release
  prometheusRule:
    enabled: true
    labels:
      release: kube-prometheus-release
    rules: {}
```

However, when I try `helm upgrade`, I get the following error:

```
Error: UPGRADE FAILED: failed to create resource: PrometheusRule.monitoring.coreos.com "docker-registry" is invalid: spec: Required value
```

It looks that there's a problem with `PrometheusRule` template.
