### ISSUE TITLE
somewhat new to kubernetes, successfully setup a dev cluster, built a container with my webapi, installed this via helm & pushed to this registry, how to i access it via kubernetes?

### ISSUE THREAD

**Issue by karezza** [twuni/docker-registry.helm#26]
I tried this:
```
    spec:
      containers:
      - image: registry-docker-registry/my_image:latest
        name: my_image
```
I see this in the documentation at the end:
```
To generate htpasswd file, run this docker command: docker run --entrypoint htpasswd registry:2 -Bbn user password > ./htpasswd.
```

I didn't expect an extra step to configure credentials because I was able to upload to the registry immediately after installing.

Do I need to generate an htpasswd file?

**Comment by karezza** [comment]
Thought I had the solution when I tried this, but not working yet:
```
    spec:
      containers:
      - image: registry-docker-registry/my_image:latest
        name: my_image
      imagePullSecrets:
      - name: registry-docker-registry-secret
```
