### ISSUE TITLE
How to add private CA

### ISSUE THREAD

**Issue by Vertiwell** [twuni/docker-registry.helm#64]
Hi, is it possible to add a private CA chain cert for trust?
I added mine by ConfigMap to /etc/ssl/certs/, however still getting:
` http: TLS handshake error from 10.42.8.197:45314: remote error: tls: bad certificate`

**Comment by canterberry** [comment]
Thanks for asking!

In your scenario, what is the client and what is the server? This will help advise on where/how to wire up the CA trust anchors.

i.e: is the error happening when trying to connect **to** the registry or **from** the registry?

**Comment by Vertiwell** [comment]
Hi, thanks for responding!
The error is when I try to connect to the registry with:
`echo ${DPASS} | docker login https://${SUBDOMAIN} --username ${DUSER} --password-stdin`

The certificate comes from Hashicorp Vault CA, via a Cert-Manager ClusterIssuer, terminated by a Traefik IngressRoute on a MetalLB load balancer.

My OS is Ubuntu.

This script installs the helm chart:
```
#!/bin/bash
### Deploying Docker Registry on Kubernetes for Debian/Ubuntu based OS
## Baseline Guide: https://faun.pub/install-a-private-docker-container-registry-in-kubernetes-7fb25820fc61
# Type of Deployment: Helm
#
## Upgrade: helm repo update && helm upgrade registry twuni/docker-registry --install -n kube-system -f /root/helm/registry/custom-values.yaml --version 2.1.0
#
### Minimum Requirements ###
## Kubernetes Cluster
## Cert-Manager
## Storage
#
## The following base packages are required:
# Helm, Package Manager
# curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
# chmod 700 get_helm.sh
# ./get_helm.sh
#
# Docker.io is required to login to the local private repository
apt-get install docker.io -y
# Htpasswd is used to create and update the flat-files used to store usernames and password
apt-get install apache2-utils -y
### Installation ###
#
## Bring in the variables from the main configuration file
# DOMAIN=example.com
# ISSUER=ca-issuer
# STORAGECLASS=longhorn
source /root/repo/deployment_config
# Set a directory to store files generated by this script (used for upgrades later)
mkdir -p /root/helm/registry
## Set Variables:
# Provide a domain
SUBDOMAIN=registry.${DOMAIN}
# Chart Version: helm repo update && helm search repo twuni/docker-registry --versions
CHARTVERSION=2.1.0
# Set directory as a variable
FILEDIR=/root/helm/registry
# Namespace for this application
NAMESPACE=registry
# Create Namespace
cat <<EOF >${FILEDIR}/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
EOF
# Apply namespace
kubectl apply -f ${FILEDIR}/namespace.yaml
#
# Create a username for the registry
DUSER=$(pwgen -csn 24 1) && \
# Create a password for the registry
DPASS=$(pwgen -csn 24 1) && \
# Create secret to store credentials
cat <<EOF >${FILEDIR}/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: ${NAMESPACE}
type: Opaque
stringData:
  docker-username: "${DUSER}"
  docker-password: "${DPASS}"
EOF
# Apply secret
kubectl apply -f ${FILEDIR}/secret.yaml
# Create a password file to be loaded into Kubernetes
htpasswd -Bbc ${FILEDIR}/registry.password ${DUSER} ${DPASS} >/dev/null 2>&1
# Add this password file to the K3S cluster using a secret
kubectl create secret -n ${NAMESPACE} generic docker-registry-htpasswd --from-file ${FILEDIR}/registry.password >/dev/null 2>&1
# Create the TLS Certificate (standard template against name.whatever.com your domain is)
cat <<EOF >${FILEDIR}/tls-cert.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert
  namespace: ${NAMESPACE}
spec:
  commonName: ${SUBDOMAIN}
  secretName: tls-cert
  dnsNames:
    - ${SUBDOMAIN}
    - registry
    - registry.registry.svc
    - registry.registry.svc.cluster.local
  issuerRef:
    name: ${ISSUER}
    kind: ClusterIssuer
EOF
# Apply the certificate
kubectl apply -f ${FILEDIR}/tls-cert.yaml
# Add the Helm Chart
helm repo add twuni https://helm.twun.io && helm repo update
# Create custom values file
# Helm Chart Values: https://github.com/twuni/docker-registry.helm/blob/main/values.yaml
cat <<EOF >${FILEDIR}/custom-values.yaml
replicaCount: 3
persistence:
  accessMode: 'ReadWriteOnce'
  enabled: true
  size: 5Gi
  storageClass: '${LOCAL}'
tlsSecretName: tls-cert
secrets:
  haSharedSecret: ""
  htpasswd: "docker-registry-htpasswd"
extraVolumeMounts:
  - name: ca-store
    mountPath: /etc/ssl/certs/custom-ca.crt
    subPath: custom-ca.crt
    readOnly: true
extraVolumes:
  - name: ca-store
    configMap:
      name: trust-operator
EOF
# Install the Helm Chart with custom values:
helm upgrade registry twuni/docker-registry --install -n ${NAMESPACE} -f ${FILEDIR}/custom-values.yaml --create-namespace --version ${CHARTVERSION}
# Clean up
# rm files containing secrets or passwords
# Wipe everything
# kubectl delete ns registry; rm -r /root/helm/registry
```

**Comment by Vertiwell** [comment]
This script exposes the registry service:
```
#!/bin/bash
### Docker Registry Access
### Minimum Requirements ###
## Requires docker-registry script
## Requires a Load Balancer (MetalLB) - See script
## Requires an Ingress Controller (Traefik) - See script
#
### Installation Steps ###
## Bring in the variables from the main configuration file
source /root/repo/deployment_config
## Set Variables:
# Set a subdomain to use
SUBDOMAIN=registry.${DOMAIN}
# Set directory as a variable
FILEDIR=/root/helm/registry
# Namespace
NAMESPACE=registry
#
# Create the Certificate (standard template against name.whatever.com your domain is)
cat <<EOF >${FILEDIR}/registry-dashboard-cert.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-dashboard-cert
  namespace: ${NAMESPACE}
spec:
  commonName: ${SUBDOMAIN}
  secretName: registry-dashboard-cert
  dnsNames:
    - ${SUBDOMAIN}
  issuerRef:
    name: ${ISSUER}
    kind: ClusterIssuer
EOF
# Create the IngressRoute to direct traffic to your application
cat <<EOF >${FILEDIR}/registry-dashboard-ingress.yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: registry-dashboard-ingress
  namespace: ${NAMESPACE}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(\`${SUBDOMAIN}\`) && PathPrefix(\`/\`)
    kind: Rule
    services:
    - name: registry-docker-registry
      port: 5000
  tls:
      secretName: registry-dashboard-cert
EOF
# Deploy Certificate and Ingress to cluster
kubectl apply $(ls ${FILEDIR}/registry-*.yaml | awk ' { print " -f " $1 } ') && sleep 5 && \
# Test
printf ""$(kubectl -n kube-system get svc traefik -o json | jq -r .status.loadBalancer.ingress[].ip)" "${SUBDOMAIN}"\n" >> /etc/hosts && \
# Get username and password from file
export DUSER=$(kubectl get secret -n registry docker-registry-secret -o jsonpath="{.data.docker-username}" | base64 --decode) && \
export DPASS=$(kubectl get secret -n registry docker-registry-secret -o jsonpath="{.data.docker-password}" | base64 --decode) && \
# Create Secret
kubectl create secret docker-registry secret --docker-server=${SUBDOMAIN} --docker-username=${DUSER} --docker-password=${DPASS} --namespace=${NAMESPACE} >/dev/null 2>&1
# Restart docker
systemctl daemon-reload && systemctl restart docker && sleep 5 && \
### Login to your private registry to test it works
echo ${DPASS} | docker login https://${SUBDOMAIN} --username ${DUSER} --password-stdin && \
# Cleanup
rm /root/.docker/config.json
# Wipe everything: kubectl delete IngressRoute docker-registry-service-dashboard-ingress -n registry; kubectl delete certificate docker-registry-service-dashboard-cert -n registry; kubectl delete secret docker-registry-service-dashboard-cert -n registry
```
