### ISSUE TITLE
Add support for storage.redirect.disable=true

### ISSUE THREAD

**Issue by FredNass** [twuni/docker-registry.helm#91]
Hello,

Thank you for providing this Helm Chart to the community. We'd like to see support for storage.redirect.disable=true as it would help in situations where S3 storage is not directly accessible to clients. Sorry for not providing the PR as it's a little beyond my skills.

**Comment by 0xDEC0DE** [comment]
Workaround
=========

In your local config:

```
docker-registry:
  configData:
    storage:
      redirect:
        disable: true
```
