### ISSUE TITLE
add redis cache support

### ISSUE THREAD

**Issue by benedikt-bartscher** [twuni/docker-registry.helm#95]
https://docs.docker.com/registry/configuration/#cache
https://github.com/bitnami/charts/tree/main/bitnami/redis

```
storage:
  cache:
    blobdescriptor: redis
    blobdescriptorsize: 10000
```

```
redis:
  addr: localhost:6379
  password: asecret
  db: 0
  dialtimeout: 10ms
  readtimeout: 10ms
  writetimeout: 10ms
  pool:inmemory
    maxidle: 16
    maxactive: 64
    idletimeout: 300s
  tls:
    enabled: false
```
