### ISSUE TITLE
`s3.regionEndpoint` requires scheme

### ISSUE THREAD

**Issue by 0xDEC0DE** [twuni/docker-registry.helm#97]
If configuring an S3-compatible object store with an endpoint that is not AWS, the transport scheme (`http`/`https`) must be provided, or the server will hang on start while logging no errors, and the liveness checks will eventually kill it, and force the pod into a crash/restart loop.

The docs provided in the `values.yaml` do not include a scheme, which leads to confusion.

# Steps to reproduce
In the `config.yaml`:
```
docker-registry:
  storage: s3
  s3:
    region: my-region
    regionEndpoint: s3.compatible.storagedevice.local
    bucket: some-bucket
```
Deploy the chart

# Expected result

The pod comes up and provides a registry

# Actual behavior

The pod cannot actually talk to the S3 service, so it silently hangs until killed by the livenessProbe checks.  Hilarity ensues.

# Workaround

Provide the transport scheme when defining the endpoint:
```
    regionEndpoint: http://s3.compatible.storagedevice.local/
```
The provided `values.yaml` contraindicates this.
